### ISSUE TITLE
update seeds

### ISSUE THREAD

**Issue by gilsdav** [hobbyfarm/hobbyfarm#1]
Example seeds didn't work in my server for 2 things:

- wrong dates format in event
- capacity (mode) missing in environment

example of "working" environment specs:

```yaml
spec:
  capacity_mode: count
  display_name: example-environment
  environment_specifics:
    access_key: ""
    endpoint: https://vmapi.hobbyfarm.192.168.1.63.xip.io
    executor_image: oats87/terraform-controller-executor:hfv1
    image: rancher/vm-ubuntu:16.04.5-server-amd64
    module: https://github.com/hobbyfarm/tf-module-rvm
    secret_key: ""
  ip_translation_map:
    172.17.2: 184.105.214
  provider: ranchervm
  template_mapping:
    ubuntu1604-docker1:
      image: rancher/vm-ubuntu:16.04.5-server-amd64
  ws_endpoint: shell.hobbyfarm.192.168.1.63.xip.io
```

example of "working" event specs:
```yaml
spec:
  access_code: example
  creator: ""
  description: ""
  end_time: Sat Nov 23 17:20:51 UTC 2019
  event_name: ""
  required_vms:
    example-environment:
      ubuntu1604-docker1: 2
  restricted_bind: false
  restricted_bind_value: ""
  scenarios:
  - example-scenario
  start_time: Sat Nov 24 17:20:51 UTC 2019

```
